// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
  guideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
  petstoreSidebar: require('./docs/petstore/sidebar.ts'), // EZT adtuk hozzá
};

export default sidebars;